import 'package:hive_flutter/hive_flutter.dart';
import 'package:logger/logger.dart';
import '../models/user_model.dart';

class HiveService {
  static late Box<UserModel> _userBox;
  static var logger = Logger(); // Cria√ß√£o de uma inst√¢ncia do Logger

  static Future<void> init() async {
    await Hive.initFlutter();

    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(UserModelAdapter());
    }

    try {
      _userBox = await Hive.openBox<UserModel>('users');
      logger.i(
        "‚úÖ Box 'users' aberta com sucesso",
      ); // Usando logger em vez de print
    } catch (e) {
      logger.e("‚ùå Erro ao abrir a box: $e"); // Usando logger para erro
      rethrow;
    }
  }

  static List<UserModel> getUsers() {
    try {
      if (!Hive.isBoxOpen('users')) {
        throw Exception('Hive box "users" not opened!');
      }

      final users = _userBox.values.toList();
      logger.i(
        "üîç Recuperado ${users.length} usu√°rios do Hive",
      ); // Usando logger para log de sucesso
      return users;
    } catch (e) {
      logger.e("‚ùå Erro ao obter usu√°rios: $e"); // Usando logger para erro
      return [];
    }
  }

  static Future<void> addUser(UserModel user) async {
    try {
      await _userBox.add(user);
      logger.i(
        "Usu√°rio ${user.name} adicionado com sucesso",
      ); // Usando logger para sucesso
    } catch (e) {
      logger.e("Erro ao adicionar usu√°rio: $e"); // Usando logger para erro
    }
  }

  static Future<void> updateUser(int index, UserModel updatedUser) async {
    try {
      await _userBox.putAt(index, updatedUser);
      logger.i(
        "Usu√°rio no √≠ndice $index atualizado com sucesso",
      ); // Usando logger para sucesso
    } catch (e) {
      logger.e("Erro ao atualizar usu√°rio: $e"); // Usando logger para erro
    }
  }

  static Future<void> deleteUser(int index) async {
    try {
      await _userBox.deleteAt(index);
      logger.i(
        "Usu√°rio no √≠ndice $index exclu√≠do com sucesso",
      ); // Usando logger para sucesso
    } catch (e) {
      logger.e("Erro ao excluir usu√°rio: $e"); // Usando logger para erro
    }
  }
}
